default: &default
  adapter: postgresql
  username: postgres
  password: 12345
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: shopify-test_development

test:
  <<: *default
  database: shopify-test_test

production:
  <<: *default
  database: shopify-test_production



